# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git
RUN npm install -g @angular/cli
RUN npm install -g pm2
RUN npm install -g http-server
WORKDIR /app
RUN git clone https://github.com/Asher018/OnlineMarketplace.git
WORKDIR /app/OnlineMarketplace
WORKDIR /app/OnlineMarketplace/client/online-marketplace
RUN git checkout devops
RUN git pull
RUN npm install
RUN npm run build
EXPOSE 8100
CMD ["pm2-runtime", "start", "http-server", "--name", "'angular-app'", "--", "-p", "8100", "-d", "false", "./dist/online-marketplace/browser"]
