# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git

RUN npm install -g pm2

WORKDIR /app
RUN git clone https://github.com/Asher018/OnlineMarketplace.git
WORKDIR /app/OnlineMarketplace
WORKDIR /app/OnlineMarketplace/server
RUN git checkout devops
RUN git pull
RUN npm install
RUN npm run build

EXPOSE 5000
CMD ["pm2-runtime", "start", "build/index.js"]